In [12]:

### variables
test1 = 'rika gajelas'

# Dataframe Original Series from table reporting.os_all_platforms
df_os = 'dataframe os'
df_trx = 'dataframe trx'


### List 
list_dataframe = [df_os,df_trx]
print(list_dataframe)

['dataframe os', 'dataframe trx']

dict_os = {
    "name":['rika','adam'],
    "age":[30,15]


}

{'name': ['rika', 'adam'], 'age': [30, 15]}
print(dict_os)

### If-else
num = 4

if num<3:
    print('rika super gajelas')
elif num == 5:
    print('rika agak gajelas')
elif num == 4:
    print('hore')
else:
    print('error code')




### looping


# for untuk kondisi yg jelas
for selection_var in list_dataframe:
    print(selection_var)


#while
status = True
num_save = 0 
while status==True:
    num_save += 1 #(num_save = num_save + 1) 
    if num_save <10:
        print(f'Rika ke {num_save}') # var_rika.format(numsave) 
    elif num_save >= 10:
        status=False



### Functions
def lib_transform_data(number=int,name_person=str):
    if number>= 10:
        print(f'tim data: {name_person} ke {number}')
    else:
        print(f'tim data: {name_person}')


lib_transform_data(number=11,name_person='rika')

['dataframe os', 'dataframe trx']
{'name': ['rika', 'adam'], 'age': [30, 15]}
hore
dataframe os
dataframe trx
Rika ke 1
Rika ke 2
Rika ke 3
Rika ke 4
Rika ke 5
Rika ke 6
Rika ke 7
Rika ke 8
Rika ke 9

In [13]:
pandas

polars
dask
connetorx


ETL -> extract, transform, load 

ELT -> extract, load, transform


numpy
sqlalchemy
psycopg2

tim data: rika ke 11

In [ ]:
pip install pandas 


pip install

In [11]:
test_var = 'adam ke {name_table}{index}'
test_var_rika = 'rika'
index_var = 3
test_var.format(name_table=test_var_rika,index=index_var)

'adam ke rika'

# Lib Pandas

In [37]:
import pandas as pd
import os


folder_config = 'folder_config'
folder_query = 'folder_query'
name_file = 'rikaagakhihi.csv'

## read csv
df = pd.read_csv('delive_all.csv')
df_top_five = df.head()

os.mkdir(folder_query)

df.to_csv(os.path.join(folder_query,name_file),index=False)

#df.to_csv(folder_config+'//'+name_file,index=False)

In [38]:
import vpluslib
import psycopg2 as psy
import sqlalchemy as sly
## read sql

conn_redshift = vpluslib.connect_init(4)


query = '''
select * from reporting.os_all_platforms limit 10
'''

df_sql = pd.read_sql(query,conn_redshift)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4628\1717492052.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sql = pd.read_sql(query,conn_redshift)

,upload_date,external_ref,content_id,delivery_id,title,short_title,provider_asset_id,provider_id,provider_code,provider,...,series_episode,series_season,episode_title,type,service,parentgenre,subgenre,product_id,product_type,rental_time
0,2024-07-12 18:10:23.000,DLVY1160486895005029,5290,44143,QA_28Noviembre23_01,QA_28Noviembre23_01,QA_28Noviembre23_01_p,adrian,NaN,NaN,...,0,0,NaN,Standalone,premium_svod,Cine,Infantil,PROD1160486951004057,SUBSCRIPTION,0
1,2024-07-12 18:10:23.000,DLVY1160606889004237,5291,44146,QA_28Noviembre23_02,QA_28Noviembre23_02,QA_28Noviembre23_04_p,adrian,NaN,NaN,...,0,0,NaN,Standalone,premium_svod,Cine,Infantil,PROD1160606946006591,SUBSCRIPTION,0
2,2024-07-12 18:10:23.000,DLVY1162887066000248,5293,52104,QA_28Noviembre23_07,QA_28Noviembre23_07,QA_28Noviembre23_05_p,adrian,NaN,NaN,...,0,0,NaN,Standalone,premium_svod,Cine,Infantil,PROD1162887185003303,SUBSCRIPTION,0
3,2024-07-12 18:10:23.000,DLVY3146463232007186,7044,47646,QA_21Diciembre23_05(01:01): 1x1,QA_21Diciembre23_05,QA_21Diciembre23_05,adrian,NaN,NaN,...,1,1,1x1,Series,premium_svod,Indefinido,NaN,PROD3146653064007124,SUBSCRIPTION,0
4,2024-07-12 18:10:23.000,DLVY0149882193001541,4258,42973,Test clip with single audio,Test clip with single audio,TestAssetSingleENGAudio,mirada_test,NaN,NaN,...,0,0,NaN,Standalone,test,Serie,Acción-Aventuras,PROD0150175591005759,SUBSCRIPTION,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20237,2024-07-12 18:10:23.000,DLVY0219228354007554,4800,52087,Manutest_DNP,Manutest_DNP,SVOD_Manu_DNP_Service_p,mirada_test,mirada_test,mirada_test,...,0,0,NaN,Standalone,test,Cine,Drama,PROD0219228479003346,SUBSCRIPTION,0
20238,2024-07-12 18:10:23.000,DLVY0222828256006431,4956,52117,Manutest_NODNPTVOD,Manutest_NODNPTVOD,SVOD_Manu_NODNP_ServiceTVOD_p,mirada_test,mirada_test,mirada_test,...,0,0,NaN,Standalone,test,Cine,Drama,PROD3258056624008447,SUBSCRIPTION,0
20239,2024-07-12 18:10:23.000,DLVY9026275655009991,4253,52133,test movie 1 audio (HD),test movie 1 audio (HD),RAQX0934629023964622,visionplus.id,visionplus.id,visionplus.id,...,0,0,NaN,Standalone,free_svod,Cine,Comedia,PROD3258445391006177,SUBSCRIPTION,0
20240,2024-07-12 18:10:23.000,DLVY7524371650000395,35531,530462,test_MM_2,test_MM_2,d4af3c5f-aacf-40a9-9fb2-86a92bf306ac,visionplus.id,visionplus.id,visionplus.id,...,0,0,NaN,Standalone,premium_svod,Documental,NaN,PROD7524371707004091,SUBSCRIPTION,0
20241,2024-07-12 18:10:23.000,DLVY0038335498004938,4279,52116,QA_15Noviembre23_02(01:01): Pruebla Piloto,QA_15Noviembre23_02,QA_15Noviembre23_02_MergeYearTitle_p,visionplus.id,visionplus.id,visionplus.id,...,1,1,Pruebla Piloto,Series,free_svod,Indefinido,NaN,PROD0038335531001448,SUBSCRIPTION,0

In [41]:
vpluslib.connect_init(4)

In [39]:
df_sql

,dtsource,created,os_name,minutes,user_id,season,episode,udkey,vsf,ebvs,ud,attempts,plays
0,Conviva Vision+,2023-04-06 16:47:43+00:00,Arab Maklum,18.222417,None,1,2,None,None,None,2524141389:2132229372:1178363218:2300416762,2524141389:2132229372:1178363218:2300416762:13...,2524141389:2132229372:1178363218:2300416762:13...
1,Conviva Vision+,2023-04-06 16:50:18+00:00,Arab Maklum,0.000000,None,1,1,None,3393326373:272793360:372367835:3477205403:4073...,None,3393326373:272793360:372367835:3477205403,3393326373:272793360:372367835:3477205403:4073...,None
2,Conviva Vision+,2023-04-06 18:36:35+00:00,Arab Maklum,20.204650,None,1,1,None,None,None,2628542372:325558079:1395357615:2226076433,2628542372:325558079:1395357615:2226076433:391...,2628542372:325558079:1395357615:2226076433:391...
3,Conviva Vision+,2023-04-06 22:17:50+00:00,Arab Maklum,0.000000,None,1,1,0,None,3311969327:2527570195:4063785768:2314398185:67...,3311969327:2527570195:4063785768:2314398185,3311969327:2527570195:4063785768:2314398185:67...,None
4,Conviva Vision+,2023-04-06 22:42:11+00:00,Arab Maklum,3.999517,None,1,1,None,None,None,259078014:2341224387:3928984583:3821197350,259078014:2341224387:3928984583:3821197350:150...,259078014:2341224387:3928984583:3821197350:150...
5,Conviva Vision+,2023-04-06 22:59:30+00:00,Arab Maklum,23.957717,8077652,1,2,49698102,None,None,339626684:1891966293:2144821318:517136043,339626684:1891966293:2144821318:517136043:3045...,339626684:1891966293:2144821318:517136043:3045...
6,Conviva Vision+,2023-04-07 00:50:29+00:00,Arab Maklum,32.057233,7738820,1,2,46986198,None,None,1645822042:247443194:3667558534:3353426709,1645822042:247443194:3667558534:3353426709:132...,1645822042:247443194:3667558534:3353426709:132...
7,Conviva Vision+,2023-04-07 01:26:14+00:00,Arab Maklum,0.000000,None,1,1,None,None,578391873:4241073944:552688397:3432792705:9428...,578391873:4241073944:552688397:3432792705,578391873:4241073944:552688397:3432792705:9428...,None
8,Conviva Vision+,2023-04-07 01:55:53+00:00,Arab Maklum,10.004733,None,1,1,0,None,None,4072734230:3879789310:391402401:3926176985,4072734230:3879789310:391402401:3926176985:754...,4072734230:3879789310:391402401:3926176985:754...
9,Conviva Vision+,2023-04-07 02:02:51+00:00,Arab Maklum,0.000000,None,1,1,None,None,4126747213:3808176503:1778329736:995893765:425...,4126747213:3808176503:1778329736:995893765,4126747213:3808176503:1778329736:995893765:425...,None

In [29]:
import os
current_script_path = os.path.abspath(__file__)
main_folder = os.path.dirname(current_script_path)

main_folder

NameError: name '__file__' is not defined

In [24]:
df

,upload_date,external_ref,content_id,delivery_id,title,short_title,provider_asset_id,provider_id,provider_code,provider,...,series_episode,series_season,episode_title,type,service,parentgenre,subgenre,product_id,product_type,rental_time
0,2024-07-12 18:10:23.000,DLVY1160486895005029,5290,44143,QA_28Noviembre23_01,QA_28Noviembre23_01,QA_28Noviembre23_01_p,adrian,NaN,NaN,...,0,0,NaN,Standalone,premium_svod,Cine,Infantil,PROD1160486951004057,SUBSCRIPTION,0
1,2024-07-12 18:10:23.000,DLVY1160606889004237,5291,44146,QA_28Noviembre23_02,QA_28Noviembre23_02,QA_28Noviembre23_04_p,adrian,NaN,NaN,...,0,0,NaN,Standalone,premium_svod,Cine,Infantil,PROD1160606946006591,SUBSCRIPTION,0
2,2024-07-12 18:10:23.000,DLVY1162887066000248,5293,52104,QA_28Noviembre23_07,QA_28Noviembre23_07,QA_28Noviembre23_05_p,adrian,NaN,NaN,...,0,0,NaN,Standalone,premium_svod,Cine,Infantil,PROD1162887185003303,SUBSCRIPTION,0
3,2024-07-12 18:10:23.000,DLVY3146463232007186,7044,47646,QA_21Diciembre23_05(01:01): 1x1,QA_21Diciembre23_05,QA_21Diciembre23_05,adrian,NaN,NaN,...,1,1,1x1,Series,premium_svod,Indefinido,NaN,PROD3146653064007124,SUBSCRIPTION,0
4,2024-07-12 18:10:23.000,DLVY0149882193001541,4258,42973,Test clip with single audio,Test clip with single audio,TestAssetSingleENGAudio,mirada_test,NaN,NaN,...,0,0,NaN,Standalone,test,Serie,Acción-Aventuras,PROD0150175591005759,SUBSCRIPTION,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20237,2024-07-12 18:10:23.000,DLVY0219228354007554,4800,52087,Manutest_DNP,Manutest_DNP,SVOD_Manu_DNP_Service_p,mirada_test,mirada_test,mirada_test,...,0,0,NaN,Standalone,test,Cine,Drama,PROD0219228479003346,SUBSCRIPTION,0
20238,2024-07-12 18:10:23.000,DLVY0222828256006431,4956,52117,Manutest_NODNPTVOD,Manutest_NODNPTVOD,SVOD_Manu_NODNP_ServiceTVOD_p,mirada_test,mirada_test,mirada_test,...,0,0,NaN,Standalone,test,Cine,Drama,PROD3258056624008447,SUBSCRIPTION,0
20239,2024-07-12 18:10:23.000,DLVY9026275655009991,4253,52133,test movie 1 audio (HD),test movie 1 audio (HD),RAQX0934629023964622,visionplus.id,visionplus.id,visionplus.id,...,0,0,NaN,Standalone,free_svod,Cine,Comedia,PROD3258445391006177,SUBSCRIPTION,0
20240,2024-07-12 18:10:23.000,DLVY7524371650000395,35531,530462,test_MM_2,test_MM_2,d4af3c5f-aacf-40a9-9fb2-86a92bf306ac,visionplus.id,visionplus.id,visionplus.id,...,0,0,NaN,Standalone,premium_svod,Documental,NaN,PROD7524371707004091,SUBSCRIPTION,0
20241,2024-07-12 18:10:23.000,DLVY0038335498004938,4279,52116,QA_15Noviembre23_02(01:01): Pruebla Piloto,QA_15Noviembre23_02,QA_15Noviembre23_02_MergeYearTitle_p,visionplus.id,visionplus.id,visionplus.id,...,1,1,Pruebla Piloto,Series,free_svod,Indefinido,NaN,PROD0038335531001448,SUBSCRIPTION,0

In [ ]:
1. query production fact payment (bulan ini)
2. query production dim product
3. fact payment join dim product (pandas join)
4. jumlah product di transacksi (pandas group by)


Product  Jumlah_trx

In [42]:
import pandas as pd
import vpluslib 

cnn = vpluslib.connect_init(4)

query_fact_payment = '''
select (start_date+interval '7 hour')::date dt,orderid_bss,dim_productid
from  production.fact_payment
where (start_date+interval '7 hour')::date between '2024-10-25' and '2024-10-28'
'''

query_dim_product = '''
select * from production.dim_product
'''

df_fact_payment = pd.read_sql(query_fact_payment,cnn)
df_dim_prod = pd.read_sql(query_dim_product,cnn)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4628\3183564585.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_fact_payment = pd.read_sql(query_fact_payment,cnn)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_4628\3183564585.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dim_prod = pd.read_sql(query_dim_product,cnn)

In [45]:
df_fact_payment.rename(columns={'dim_productid':'id_sama'},inplace=True)
df_dim_prod.rename(columns={'id':'id_sama'},inplace=True)

In [47]:
data_baru = df_fact_payment.merge(df_dim_prod, on='id_sama', how='left')
data_baru

,dt,orderid_bss,id_sama,product_id,package_id,created,package_group,product_name,status
0,2024-10-25,ORDER144755481729768635435,1666,1145,1043.0,2024-01-09 11:57:21.485381+00:00,Premium dengan Sports,Premium + Sports 30 Hari,BSS
1,2024-10-26,ORDER374332161729867445726,1666,1145,1043.0,2024-01-09 11:57:21.485381+00:00,Premium dengan Sports,Premium + Sports 30 Hari,BSS
2,2024-10-26,ORDER117394941729875773316,802,1200,1041.0,2024-02-19 03:36:14.125532+00:00,Premium,Bundling Telkomsel Premium 30D 3GB,BSS
3,2024-10-25,ORDER359834661729764406148,1666,1145,1043.0,2024-01-09 11:57:21.485381+00:00,Premium dengan Sports,Premium + Sports 30 Hari,BSS
4,2024-10-25,ORDER97095691729785321221,1666,1145,1043.0,2024-01-09 11:57:21.485381+00:00,Premium dengan Sports,Premium + Sports 30 Hari,BSS
...,...,...,...,...,...,...,...,...,...
26527,2024-10-26,ORDER196539001729866693822,578,1221,1687.0,2024-03-15 09:32:47.459728+00:00,Combo MeVVah Viu,Combo MeVVah,BSS
26528,2024-10-28,ORDER347700351730076196036,883,2173,2920.0,2024-08-15 04:29:15.903961+00:00,Premium Movies,Premium Movies 30 Hari,BSS
26529,2024-10-28,ORDER15021691730092212945,138,2171,2919.0,2024-08-15 04:26:23.058749+00:00,Premium Ultimate,Premium Ultimate 30 Days,BSS
26530,2024-10-25,ORDER147223551729799105535,625,2270,3183.0,2024-09-20 03:58:56.649970+00:00,beIN SPORTS,beIN SPORTS 30 Hari,BSS
26531,2024-10-28,ORDER122020671730038988239,1666,1145,1043.0,2024-01-09 11:57:21.485381+00:00,Premium dengan Sports,Premium + Sports 30 Hari,BSS

In [48]:
data_baru_2 = df_fact_payment.join(df_dim_prod, on='id_sama', how='left', lsuffix='_payment', rsuffix='_product')

In [49]:
data_baru_2

,dt,orderid_bss,id_sama_payment,id_sama_product,product_id,package_id,created,package_group,product_name,status
0,2024-10-25,ORDER144755481729768635435,1666,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,2024-10-26,ORDER374332161729867445726,1666,NaN,NaN,NaN,NaT,NaN,NaN,NaN
2,2024-10-26,ORDER117394941729875773316,802,NaN,NaN,NaN,NaT,NaN,NaN,NaN
3,2024-10-25,ORDER359834661729764406148,1666,NaN,NaN,NaN,NaT,NaN,NaN,NaN
4,2024-10-25,ORDER97095691729785321221,1666,NaN,NaN,NaN,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
26527,2024-10-26,ORDER196539001729866693822,578,3362.0,4829.0,NaN,2023-08-28 01:59:18+00:00,Premium dengan Sports,Vision+ LMAC PS 365 Bronze 8 Sep,Legacy
26528,2024-10-28,ORDER347700351730076196036,883,NaN,NaN,NaN,NaT,NaN,NaN,NaN
26529,2024-10-28,ORDER15021691730092212945,138,1265.0,1061.0,1043.0,2024-01-09 11:57:21.485381+00:00,Premium dengan Sports,Voucher TIX ID Periode: 30 hari+30 hari,BSS
26530,2024-10-25,ORDER147223551729799105535,625,NaN,NaN,NaN,NaT,NaN,NaN,NaN
26531,2024-10-28,ORDER122020671730038988239,1666,NaN,NaN,NaN,NaT,NaN,NaN,NaN